name: Experiment
on: 
  schedule:
  - cron: '0 * * * *'

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with: { ref: master }
    - name: List files
      run: ls
