name: First action
on:
  push:
    branches: [ master ]

jobs:
  job1:
    name: List
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: List files
        run: ls
        with:
          event-type: my-event
          client-payload: '{ "env": "staging" }'
