name: Triggered action
on:
  repository_dispatch:
    types: [my-event]

jobs:
  test-ui-staging:
    name: Test UI staging
    runs-on: ubuntu-latest
    if: ${{ github.event.client_payload.env == 'staging' }}

    steps:
      - name: Say hello
        run: echo $ENV_VAR
        env:
          ENV_VAR: 'STAGING'

  test-ui-prod:
    name: Test UI production
    runs-on: ubuntu-latest
    if: ${{ github.event.client_payload.env == 'production' }}

    steps:
      - name: Say hello
        run: echo $ENV_VAR
        env:
          ENV_VAR: 'PROD'
