name: Second action
on:
  workflow_run:
    workflows: ["First action"]
    types:
      - completed

jobs:
  job2:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: List files
        run: ls
